#ifndef ARCH_X86_64_KERNEL_H_
#define ARCH_X86_64_KERNEL_H_


// START macros must have the same value in the kernel linker script
#define KERNEL_PHYSICAL_START 0x0000000000400000L

#define KERNEL_GDT_ENTRY 1

#ifndef NO_CONTROL_REGISTER_INCLUDE
#include "arch/x86_64/control_register.h"
#endif

#define KERNEL_CR0 (CONTROL_REGISTER0_PAGE | CONTROL_REGISTER0_MONITOR_COPROCESSOR | CONTROL_REGISTER0_PROTECTED_MODE_ENABLED | CONTROL_REGISTER0_EXTENSION_TYPE)
#define KERNEL_CR4 (CONTROL_REGISTER4_PHYSICAL_ADDRESS_EXTENSION | CONTROL_REGISTER4_OSFXSR | CONTROL_REGISTER4_OSXMMEXCPT)

#endif
