#ifndef SIZES_H_
#define SIZES_H_

#define TWO_MEGABYTES_SHIFT 21
#define TWO_MEGABYTES (1 << TWO_MEGABYTES_SHIFT)

#define FOUR_KILOBYTES_SHIFT 12
#define FOUR_KILOBYTES (1 << FOUR_KILOBYTES_SHIFT)

#endif
